name: deploy-gh-pages
run-name: ${{ github.actor }} is deploying gh-pages
on: 
  push: 
    branch: 
      -main
jobs: 
  deploy-gh-pages: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
        with: 
          token: ${{ github.token }}
    - uses: actions/setup-node@v3
      with: 
        node-version: "16"
    - run: |
        git config --global uer.email "${{ github.event.pusher.email }}"
        git config --global user.name "${{ github.actor }}"
    # - name: Install yarn
    #   run: npm install -g yarn
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: PUBLIC_URL=/${{ gitub.event.repository.name }} npm run build 
    - name: Deploy gh-pages
      run: |
        mkdir -p ./dist/gh-pages
        git init -b gh-pages ./dist/gh-pages
        cd ./dist/gh-pages
        git add remote -t gh-pages orgin \
        https://git:${{ github.token }}@github.com/${{  github.repository }}.git
        git pull origin gh-pages
        rm -rf./*
        cp -rf ../build/* ./
        git add .
        git commit -m "${{ github.actor }} deploy"
        git push origin gh-pages
        cd ..
